# Generated by Django 3.2.9 on 2021-11-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211110_0612'),
        ('students', '0002_auto_20211110_0612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourse',
            new_name='StudentCourses',
        ),
    ]
