# Generated by Django 3.2.9 on 2021-11-10 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration', models.IntegerField()),
                ('max_students', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
    ]
